[package]
name = "jetpack"
edition = "2021"
authors = ["Matthew Polak <git@matteopolak.com>"]
license = "MIT"

[dependencies]
ira.workspace = true
ira_drum.workspace = true
basic.path = "../basic"

[features]
default = ["client", "server"]
client = ["ira/client"]
server = ["ira/server"]

