[package]
name = "basic"
edition = "2021"
authors = ["Matthew Polak <git@matteopolak.com>"]
license = "MIT"

[dependencies]
ira.path = "../../ira"
ira_drum.path = "../../ira_drum"

[features]
default = []
client = ["ira/client"]
server = ["ira/server"]

