[package]
name = "basic"
edition = "2021"
authors = ["Matthew Polak <git@matteopolak.com>"]
license = "MIT"

[dependencies]
ira.workspace =true
ira_drum.workspace = true

[features]
default = []
client = ["ira/client"]
server = ["ira/server"]

